function run_todos()
    % =====================================================================
    %  MENÚ INTERACTIVO - PARCIAL 2 (Adonais)
    %  Lanza cualquiera de los scripts del parcial desde un solo menú.
    %  Uso:   run_todos
    % =====================================================================
    % Nota: cada script hace 'clear' al inicio; por eso este menú es una
    % FUNCIÓN y reconstruye sus variables en cada vuelta del bucle.

    while true
        opciones = { ...
            'T1 - Interpolación de Newton', ...
            'T1 - Interpolación de Lagrange', ...
            'T2 - Trazador cúbico (spline)', ...
            'T3 - Mínimos cuadrados', ...
            'T4 - Diferenciación numérica', ...
            'T5 - Trapecio compuesta', ...
            'T5 - Simpson 1/3', ...
            'T5 - Simpson 3/8', ...
            'T6 - Euler (EDO)', ...
            'T6 - Euler mejorado y RK4', ...
            'SALIR' };

        archivos = { ...
            't1_interpolacion_newton', ...
            't1_interpolacion_lagrange', ...
            't2_spline_cubico', ...
            't3_minimos_cuadrados', ...
            't4_diferenciacion', ...
            't5_trapecio', ...
            't5_simpson13', ...
            't5_simpson38', ...
            't6_euler', ...
            't6_euler_mejorado_rk4' };

        c = menu('PARCIAL 2 - elige un tema', opciones{:});

        if c == numel(opciones) || c == 0
            fprintf('\nFin del menú. ¡Suerte en el parcial!\n\n');
            break;
        end

        fprintf('\n>>> Ejecutando: %s\n', opciones{c});
        run(archivos{c});      % corre el script elegido (workspace compartido)
    end
end
